### ISSUE TITLE
yaml sb and zt semplification

### ISSUE THREAD

**Issue by obar1pr** [obar1/0to100#125]
- [ ] from current to 

```yaml
# zo
type: zero-to-one-hundred-map
repo:
  path: "./0to100"
  idx_id: "toc.md"
  idx_sort: "00:00:00" # order by modified date
legend:
  icons:
    - name: Project
      icon: ":cyclone:"
      regex: "project"

# sb
type: safari-books-map
download_engine_path: "safaribooks/safaribooks.py"
download_engine_books_path: "safaribooks/Books"
download_books: false
split_pdf_pages: 0
oreilly_secrets:
  username: "username"
  password: "userpassword"
legend:
  icons:
    - name: Book
      icon: ":cyclone:"
      regex: "978"
    - name: Event
      icon: ":cyclone:"
      regex: "event"
    - name: Course
      icon: ":cyclone:"
      regex: "course"
```

- [ ] change tests and test folder name

- [ ] replace zt to zo
