### ISSUE TITLE
add more sample for commons sites like yt udemy coursera etc

### ISSUE THREAD

**Issue by obar1pr** [obar1/0to100#144]
ex
```
type: zero-to-one-hundred-map
repo:
  path: "."
  idx_id: "toc_zo.md"
  idx_sort: "00:00:00" # order by modified date
legend:
  icons:
    - name: course
      icon: ":cyclone:"
      regex: "course"
    - name: youtube
      icon: "<img src='https://upload.wikimedia.org/wikipedia/commons/b/b8/YouTube_Logo_2017.svg' alt='YouTube Logo' width='64'>"
      regex: "youtube"
    - name: udemy
      icon: "<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Udemy_logo.svg/1920px-Udemy_logo.svg.png' alt='Udemy' width='64'>"
      regex: "udemy"
      
      
```

- [ ] change test
- [ ] add some sample in readme
